version: "3.0"

services:
  #
  # The Oracle DB Definition
  #
  idmdb:
    image: oracle/idm/db:${DC_IDM_DB_VERSION}-${DC_IDM_DB_EDITION}
    ports:
      - "${DC_ORCL_PORT}:1521"
      - "${DC_ORCL_OEM_PORT}:5500"
    container_name: "idmdb${IDM_INSTANCE}"
    hostname: "idmdb${IDM_INSTANCE}"
    volumes:
      - oimdatabase:/opt/oracle/oradata
    environment:
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
      - DB_EDITION=${DC_IDM_DB_EDITION}
    build:
      context: ./OracleDatabaseStandard/dockerfiles/${DC_IDM_DB_VERSION}
      args:
        - ORACLE_SID=${ORACLE_SID}
        - ORACLE_PDB=${ORACLE_PDB}
        - ORACLE_PWD=${ORACLE_PWD}
        - DB_EDITION=${DC_IDM_DB_EDITION}
  #
  # The Install domain container
  #
  idminstall:
    image: oracle/idm/install:${DC_IDM_VERSION}
    container_name: "idminstall${IDM_INSTANCE}"
    hostname: "idminstall${IDM_INSTANCE}"
    depends_on:
      - "idmdb"
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    volumes:
      - "domainhome:/u01/oracle/user_projects"
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ADMIN_HOST=${ADMIN_HOST}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${ORACLE_PDB}
      - DB_PASSWORD=${ORACLE_PWD}
      - DB_SCHEMA_PASSWORD=${DB_SCHEMA_PASSWORD}
      - RCUPREFIX=${RCUPREFIX}
      - OIM_HOST=oim${IDM_INSTANCE}
      - SOA_HOST=soa${IDM_INSTANCE}
      - DOMAIN_ROOT=/u01/oracle/user_projects/domains
      - DOMAIN_NAME=idm_domain
      - DISPLAY=$DISPLAY
    build:
      context: ./OracleIDM/dockerfiles/${DC_IDM_VERSION}
      dockerfile: Dockerfile.idm.install
      args:
        - ADMIN_HOST=${ADMIN_HOST}
        - ADMIN_PORT=${ADMIN_PORT}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${ORACLE_PDB}
        - DB_PASSWORD=${ORACLE_PWD}
        - DB_SCHEMA_PASSWORD=${DB_SCHEMA_PASSWORD}
        - RCUPREFIX=${RCUPREFIX}
        - OIM_HOST=oim${IDM_INSTANCE}
        - SOA_HOST=soa${IDM_INSTANCE}
  #
  # The Admin Server
  #
  idmas:
    image: oracle/idm:${DC_IDM_VERSION}
    container_name: "idmas${IDM_INSTANCE}"
    hostname: "idmas${IDM_INSTANCE}"
    depends_on:
      - "idmdb"
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/startAS.sh"
    ports:
      - "7001:7001"
    volumes:
      - "domainhome:/u01/oracle/user_projects"
    environment:
      - ADMIN_HOST=${ADMIN_HOST}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${ORACLE_PDB}
      - DB_PASSWORD=${ORACLE_PWD}
      - DB_SCHEMA_PASSWORD=${DB_SCHEMA_PASSWORD}
      - RCUPREFIX=${RCUPREFIX}
      - OIM_HOST=oim${IDM_INSTANCE}
      - SOA_HOST=soa${IDM_INSTANCE}
      - DOMAIN_ROOT=/u01/oracle/user_projects/domains
      - DOMAIN_NAME=idm_domain
    build:
      context: ./OracleIDM/dockerfiles/${DC_IDM_VERSION}
      args:
        - ADMIN_HOST=${ADMIN_HOST}
        - ADMIN_PORT=${ADMIN_PORT}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${ORACLE_PDB}
        - DB_PASSWORD=${ORACLE_PWD}
        - DB_SCHEMA_PASSWORD=${DB_SCHEMA_PASSWORD}
        - RCUPREFIX=${RCUPREFIX}
        - OIM_HOST=oim${IDM_INSTANCE}
        - SOA_HOST=soa${IDM_INSTANCE}

  #
  # The SOA Managed Server
  #
  soa:
    image: oracle/idm:${DC_IDM_VERSION}
    container_name: "soa${IDM_INSTANCE}"
    hostname: "soa${IDM_INSTANCE}"
    depends_on:
      - "idmas"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - ADMIN_HOST=${ADMIN_HOST}
      - ADMIN_PORT=${ADMIN_PORT}
      - MANAGED_SERVER=soa_server1
    volumes:
      - "domainhome:/u01/oracle/user_projects"
  #
  # The OIM Managed Server
  #
  oim:
    image: oracle/idm:${DC_IDM_VERSION}
    container_name: "oim${IDM_INSTANCE}"
    hostname: "oim${IDM_INSTANCE}"
    depends_on:
      - "soa"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "14000:14000"
    environment:
      - ADMIN_HOST=${ADMIN_HOST}
      - ADMIN_PORT=${ADMIN_PORT}
      - MANAGED_SERVER=oim_server1
    volumes:
      - "domainhome:/u01/oracle/user_projects"
  #
  # Volumes
  #

volumes:
  oimdatabase:
  domainhome:

# sudo /usr/local/bin/docker-compose exec idmdb /opt/oracle/product/19c/dbhome_1/bin/sqlplus system/SysMyPasswd123@//localhost:1521/IDMPDB
# sudo /usr/local/bin/docker-compose exec idmdb /opt/oracle/product/19c/dbhome_1/bin/sqlplus / as sysdba
# CREATE RESTORE POINT docker_after_first_start GUARANTEE FLASHBACK DATABASE;
# CREATE RESTORE POINT docker_after_first_start;
# SELECT NAME, SCN, TIME, DATABASE_INCARNATION#,GUARANTEE_FLASHBACK_DATABASE,STORAGE_SIZE FROM V$RESTORE_POINT;