version: "3.0"

services:
  #
  # The Oracle DB Definition
  #
  idmdb:
    image: oracle/idm/database:${DC_IDM_DB_VERSION}-${DC_IDM_DB_EDITION}
    ports:
      - "${DC_ORCL_PORT}:1521"
      - "${DC_ORCL_OEM_PORT}:5500"
    container_name: idmdb
    volumes:
      - ${DC_ORCL_DBDATA}:/opt/oracle/oradata
    build:
      context: ./OracleDatabaseStandard/dockerfiles/${DC_IDM_DB_VERSION}
      args:
        - ORACLE_SID=${DC_ORCL_SID}
        - ORACLE_PDB=${DC_ORCL_PDB}
        - ORACLE_PWD=${ORACLE_PWD}
  #
  # The SOA Admin Server
  #
  idmas:
    image: oracle/idm:${DC_IDM_VERSION}
    container_name: idmas
    depends_on:
      - "idmdb"
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    volumes:
      - ${DC_DDIR_USER_PROJECTS}:/u01/oracle/user_projects
    build:
      context: ./OracleIDM/dockerfiles/${DC_IDM_VERSION}
      args:
        - ADMIN_HOST=${ADMIN_HOST}
        - ADMIN_PASSWORD=${DC_ADMIN_PWD}
        - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${DC_ORCL_PDB}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_SCHEMA_PASSWORD=${DB_PASSWORD}
        - RCUPREFIX=${RCUPREFIX}
  #
  # The SOA Managed Server
  #
  soams:
    image: oracle/idm:${DC_IDM_VERSION}
    container_name: soams
    depends_on:
      - "idmas"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - ADMIN_PORT=7001
      - adminhostname=${ADMIN_HOST}
      - adminport=7001
      - MANAGED_SERVER=soa_server1
    volumes:
      - ${DC_DDIR_USER_PROJECTS}:/u01/oracle/user_projects

  #
  # The OIM Managed Server
  #

  idmms:
    image: oracle/idm:${DC_IDM_VERSION}
    container_name: oimms
    depends_on:
      - "soams"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - ADMIN_PORT=7001
      - adminhostname=${ADMIN_HOST}
      - adminport=7001
      - MANAGED_SERVER=oim_server1
    volumes:
      - ${DC_DDIR_USER_PROJECTS}:/u01/oracle/user_projects
